In [1]:
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/dataprofessor/data/master/delaney_solubility_with_descriptors.csv')
df.head()

   MolLogP    MolWt  NumRotatableBonds  AromaticProportion  logS
0   2.5954  167.850                0.0                 0.0 -2.18
1   2.3765  133.405                0.0                 0.0 -2.00
2   2.5938  167.850                1.0                 0.0 -1.74
3   2.0289  133.405                1.0                 0.0 -1.48
4   2.9189  187.375                1.0                 0.0 -3.04

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1144 entries, 0 to 1143
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   MolLogP             1144 non-null   float64
 1   MolWt               1144 non-null   float64
 2   NumRotatableBonds   1144 non-null   float64
 3   AromaticProportion  1144 non-null   float64
 4   logS                1144 non-null   float64
dtypes: float64(5)
memory usage: 44.8 KB

In [4]:
df.columns

Index(['MolLogP', 'MolWt', 'NumRotatableBonds', 'AromaticProportion', 'logS'], dtype='object')

In [6]:
df.isnull().sum()

MolLogP               0
MolWt                 0
NumRotatableBonds     0
AromaticProportion    0
logS                  0
dtype: int64

In [7]:
X = df.drop(['logS'], axis=1)
y = df['logS']

In [8]:
X

      MolLogP    MolWt  NumRotatableBonds  AromaticProportion
0     2.59540  167.850                0.0            0.000000
1     2.37650  133.405                0.0            0.000000
2     2.59380  167.850                1.0            0.000000
3     2.02890  133.405                1.0            0.000000
4     2.91890  187.375                1.0            0.000000
...       ...      ...                ...                 ...
1139  1.98820  287.343                8.0            0.000000
1140  3.42130  286.114                2.0            0.333333
1141  3.60960  308.333                4.0            0.695652
1142  2.56214  354.815                3.0            0.521739
1143  2.02164  179.219                1.0            0.461538

[1144 rows x 4 columns]

In [9]:
y

0      -2.180
1      -2.000
2      -1.740
3      -1.480
4      -3.040
        ...
1139    1.144
1140   -4.925
1141   -3.893
1142   -3.790
1143   -2.581
Name: logS, Length: 1144, dtype: float64

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=100)

In [15]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(915, 4)
(229, 4)
(915,)
(229,)

# Model Build

In [17]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(X_train, y_train)

LinearRegression()

In [19]:
output1 = lr.predict(X_test)
output1

array([-3.05722870e+00, -7.77785827e+00, -2.55016650e+00, -2.01523582e+00,
       -2.06375990e+00, -9.99672215e-01, -5.94603364e-01, -5.53626003e-01,
       -5.72200956e+00, -3.94006681e+00, -3.95496755e+00, -2.29737009e+00,
       -1.48980354e+00, -1.48988982e+00, -4.64510806e+00, -1.90396018e+00,
       -1.51566313e+00, -3.16424605e+00, -3.70863920e+00, -5.58105660e+00,
       -3.25038467e+00, -5.04235077e+00, -5.69194881e+00, -2.14339849e+00,
       -4.35689341e+00, -5.03964756e+00, -3.10383618e+00, -4.40286964e+00,
       -4.21276272e+00,  5.56508349e-01, -1.45537678e+00, -4.41027396e+00,
       -2.59668773e+00, -1.53336276e+00, -5.55749874e-01, -1.67111795e+00,
       -2.78163675e+00, -3.15395565e+00, -5.27083361e+00, -1.75321446e+00,
       -1.53350725e+00, -2.01255666e+00, -6.57559167e+00, -7.89433046e+00,
       -5.76437127e+00, -4.16422068e+00, -3.43694663e+00,  1.43834212e+00,
       -1.12679105e-02, -2.34521849e+00, -1.86480046e+00, -5.03964756e+00,
        8.55886378e-01, -3.17679292e+00, -5.06764094e+00, -1.99464442e+00,
       -7.77785827e+00, -1.21764693e+00, -9.09541075e-01, -5.04235077e+00,
       -2.43898748e+00, -2.84034045e+00, -2.53403538e+00, -2.36170311e+00,
       -1.63103729e+00, -1.53182046e+00, -3.23931568e+00, -2.88008616e+00,
       -1.88300518e+00, -3.21582220e+00, -3.40245202e+00, -9.01813905e-01,
       -4.82308940e+00, -7.69116343e-01, -7.12894308e+00, -1.05440427e+01,
       -1.95444152e+00, -3.50194744e+00, -7.18167736e+00, -6.01555673e+00,
       -2.08189806e+00, -2.31652280e+00, -3.44556948e+00, -2.05480142e+00,
       -6.01555673e+00, -2.88308299e+00, -4.84867198e+00, -3.51006495e-01,
       -3.54726250e+00, -1.21057919e+00, -4.36658559e+00, -4.21815903e-01,
       -1.63103729e+00, -2.51604291e+00, -2.16707077e+00, -1.48726025e+00,
       -3.20864450e+00, -1.51411141e+00, -1.65033691e+00, -3.66287663e+00,
       -3.26968347e+00, -3.94492313e+00, -4.22509088e+00, -3.68794650e+00,
       -5.98734972e+00, -1.43710934e+00, -1.97653920e+00, -1.85076729e+00,
       -1.14179382e+00, -3.07730828e+00, -4.84867198e+00, -2.19679345e+00,
       -1.68737438e+00, -2.20390218e+00,  1.89408269e+00, -3.61322115e+00,
       -2.79173430e+00, -2.41564138e+00, -7.53910534e-01, -8.54744860e-01,
       -9.20407401e-02, -6.14209981e+00, -3.79386016e+00, -7.77785827e+00,
       -1.79874130e+00, -2.50544035e+00, -3.77102985e+00, -2.25250766e+00,
       -2.57788713e+00, -2.06375990e+00, -3.33843958e+00, -1.03912484e+00,
       -6.68946164e+00, -1.91112045e+00, -2.58735850e+00, -2.19902800e+00,
       -1.90219551e+00, -2.81396751e+00, -4.16972153e+00, -5.72200956e+00,
       -1.60816482e+00, -3.68121117e+00, -4.60929775e+00, -2.45888480e+00,
        1.13185484e+00, -1.69279625e+00, -7.09025955e+00, -3.79386016e+00,
       -2.99712058e+00, -5.79600137e+00, -2.44845780e+00, -5.29399242e+00,
       -5.29389899e-01, -3.53652118e+00, -3.51200413e+00, -2.02419300e+00,
       -4.47466933e+00, -3.63836536e+00, -4.56596939e+00, -5.57842703e+00,
       -5.30676136e+00, -2.39225449e+00, -4.88290144e+00, -2.61359308e+00,
       -3.11841945e+00, -2.05580278e+00, -1.64987419e+00, -4.91881901e+00,
       -3.93774254e+00, -4.26411548e+00, -3.15082845e+00, -3.49352203e+00,
       -3.81768831e+00, -3.77197350e+00, -2.55016650e+00, -1.97653920e+00,
       -2.59432621e+00, -5.38480406e+00, -5.44932525e+00, -3.04107137e+00,
       -1.87252408e+00, -2.25124657e+00, -2.89215707e+00, -3.46087334e+00,
       -6.06861986e+00, -1.89916369e+00, -1.98035105e+00, -2.45036038e+00,
       -2.79393037e+00, -4.76010415e+00, -1.72379306e+00, -7.09025955e+00,
       -2.86880150e+00, -2.70674744e+00, -4.36825704e+00, -3.11841945e+00,
       -3.85805633e+00,  9.78662246e-03, -4.47466933e+00, -6.08708502e+00,
       -5.19970454e+00, -6.40483191e+00, -4.10155218e+00, -1.07044752e+00,
        1.99249372e+00, -3.63698515e+00, -8.50933009e-01, -3.26770298e+00,
       -4.78343575e+00, -1.48988982e+00, -2.24629276e+00, -4.13247222e+00,
       -4.36873484e+00, -1.89724815e+00, -1.50596465e+00, -1.16713539e-02,
       -1.73602998e+00, -2.34521849e+00, -4.54942814e-01, -4.18812419e+00,
       -1.87770440e+00, -3.70838271e+00, -1.59899899e+00, -3.26143822e+00,
       -4.17623614e+00, -6.67872053e+00, -1.23069039e+00, -3.14545964e+00,
       -4.79863925e+00])

## Performance

In [21]:
from sklearn.metrics import r2_score, mean_squared_error

print(r2_score(y_test, output1))
print(mean_squared_error(y_test, output1))

0.7891616188563282
1.0206953660861033

In [23]:
from sklearn.ensemble import RandomForestRegressor
rf = RandomForestRegressor()
rf.fit(X_train, y_train)

RandomForestRegressor()

In [25]:
output2 = rf.predict(X_test)
output2

array([-3.23999333e+00, -8.14085827e+00, -2.27434210e+00, -1.44807940e+00,
       -5.69121667e-01, -1.93573333e+00, -3.60000000e-03, -1.99988000e+00,
       -6.27587337e+00, -3.88189000e+00, -4.56279000e+00, -1.86704500e+00,
       -2.29216333e+00, -1.12459893e+00, -4.12330000e+00, -1.01620714e+00,
       -7.01160000e-01, -3.87683000e+00, -3.58001000e+00, -4.92832000e+00,
       -2.50657667e+00, -5.52872734e+00, -6.63883131e+00, -3.50267500e+00,
       -4.22584000e+00, -4.84398767e+00, -4.65731000e+00, -4.21339667e+00,
       -4.51917333e+00,  5.51460000e-01, -2.73193000e+00, -4.20550000e+00,
       -2.61566333e+00, -8.07133333e-01, -7.36665238e-01, -2.49206071e+00,
       -3.12543000e+00, -2.50773000e+00, -5.19700000e+00, -8.70643333e-01,
       -5.01010000e-01, -1.73372667e+00, -6.41217286e+00, -6.77308000e+00,
       -6.35822111e+00, -4.33360333e+00, -3.90378000e+00, -9.26616667e-02,
       -1.81695667e+00, -1.44949024e+00, -1.40465833e+00, -4.84398767e+00,
       -3.37190000e-01, -3.13542000e+00, -5.03977017e+00, -1.80513333e+00,
       -8.14085827e+00, -5.11875000e-01, -2.11917000e+00, -5.52872734e+00,
       -2.64532778e+00, -2.09653000e+00, -2.03713333e+00, -2.07920000e+00,
        3.20120000e-01, -1.04439333e+00, -3.34366333e+00, -2.80145500e+00,
       -1.87784500e+00, -3.84675667e+00, -3.36061000e+00, -4.73300000e-01,
       -4.35378429e+00, -1.75920000e-01, -4.28579714e+00, -8.50958833e+00,
       -2.29601000e+00, -4.33398500e+00, -7.11162000e+00, -8.25935250e+00,
       -1.79038000e+00, -2.54057000e+00, -3.37714000e+00, -1.69650000e+00,
       -8.25935250e+00, -3.04997833e+00, -5.95202286e+00, -1.40900000e-01,
       -3.35704833e+00, -2.51030000e+00, -5.01990500e+00, -1.28458000e+00,
        3.20120000e-01, -2.67112000e+00, -2.06629667e+00, -7.09047381e-01,
       -2.78561333e+00, -2.04500000e+00, -1.80330000e+00, -3.83932833e+00,
       -3.18845000e+00, -3.51478333e+00, -4.31992595e+00, -3.35479000e+00,
       -5.79383333e+00, -1.54410000e-01, -1.26701595e+00, -2.22080000e+00,
       -1.38691500e+00, -2.64889667e+00, -5.95202286e+00, -1.88074182e+00,
       -2.54712024e+00, -2.30060000e+00, -1.16601667e-01, -3.89684000e+00,
       -4.22174000e+00, -4.15410000e+00, -1.71377000e+00, -4.55040000e-01,
        1.05150000e+00, -6.08776857e+00, -2.62164467e+00, -8.14085827e+00,
       -2.30642000e+00, -2.69778238e+00, -4.12064333e+00, -3.66096167e+00,
       -2.04836833e+00, -5.69121667e-01, -2.79532000e+00, -5.49135000e-01,
       -6.71140000e+00, -1.77946000e+00, -2.51792333e+00, -2.78365111e+00,
       -1.67819682e+00, -2.63907262e+00, -3.61350667e+00, -6.27587337e+00,
       -2.15216833e+00, -2.80756000e+00, -6.19838286e+00, -2.73402905e+00,
       -5.23170000e-01, -2.35184476e+00, -7.48742571e+00, -2.62164467e+00,
       -2.84196000e+00, -6.02256000e+00, -2.11359000e+00, -5.76204278e+00,
       -1.55138000e+00, -2.88464000e+00, -3.50968500e+00, -2.34880333e+00,
       -3.76705000e+00, -3.28917500e+00, -4.36823333e+00, -4.90458000e+00,
       -5.48809000e+00, -2.17999167e+00, -4.76823517e+00, -3.34018000e+00,
       -1.50885762e+00,  3.46000278e-01, -1.96130000e+00, -4.64191050e+00,
       -3.94297286e+00, -3.81424000e+00, -2.78908000e+00, -3.39646667e+00,
       -4.25098000e+00, -3.62701833e+00, -2.27434210e+00, -1.26701595e+00,
       -4.24070000e+00, -5.21136000e+00, -5.48347000e+00, -3.04390500e+00,
       -2.08684500e+00, -2.85135333e+00, -2.53760000e+00, -3.78693000e+00,
       -6.34104036e+00, -1.54849833e+00, -1.28723595e+00, -9.88163333e-01,
       -3.75732667e+00, -4.30205000e+00, -1.72297500e+00, -7.48742571e+00,
       -2.70220500e+00, -3.36948000e+00, -3.79648667e+00, -1.50885762e+00,
       -3.54514833e+00,  3.54300000e-02, -3.76705000e+00, -8.64495250e+00,
       -4.88754000e+00, -6.89530817e+00, -4.42886000e+00, -1.64675667e+00,
        2.04820000e-01, -3.24699000e+00, -1.67600000e-01, -3.34907333e+00,
       -4.52310933e+00, -1.12459893e+00, -1.63291500e+00, -4.23630000e+00,
       -4.78346833e+00, -1.69950548e+00, -1.78450000e+00,  1.06330000e+00,
       -9.89766667e-01, -1.44949024e+00,  2.60700000e-01, -3.78950000e+00,
       -1.61737500e+00, -4.46777909e+00, -8.74674643e-01, -4.43159500e+00,
       -3.88588000e+00, -8.10984250e+00, -1.17978000e+00, -2.98941500e+00,
       -4.59808000e+00])

In [26]:
print(r2_score(y_test, output2))
print(mean_squared_error(y_test, output2))

0.8652217399918412
0.6524786649055746

In [32]:
pd.DataFrame({'Actual':y_test,'Predicted':output1})

      Actual  Predicted
822   -3.380  -3.239993
118   -8.010  -8.140858
347   -2.160  -2.274342
1123  -1.170  -1.448079
924   -0.730  -0.569122
...      ...        ...
1114  -4.130  -3.885880
427   -9.018  -8.109843
711   -0.600  -1.179780
4     -3.040  -2.989415
948   -2.900  -4.598080

[229 rows x 2 columns]