In [ ]:
import pandas as pd
import numpy as np

df = pd.read_csv('/content/garments_worker_productivity.csv')
df

,date,quarter,department,day,team,targeted_productivity,smv,wip,over_time,incentive,idle_time,idle_men,no_of_style_change,no_of_workers,actual_productivity
0,1/1/2015,Quarter1,sweing,Thursday,8,0.80,26.16,1108.0,7080,98,0.0,0,0,59.0,0.940725
1,1/1/2015,Quarter1,finishing,Thursday,1,0.75,3.94,NaN,960,0,0.0,0,0,8.0,0.886500
2,1/1/2015,Quarter1,sweing,Thursday,11,0.80,11.41,968.0,3660,50,0.0,0,0,30.5,0.800570
3,1/1/2015,Quarter1,sweing,Thursday,12,0.80,11.41,968.0,3660,50,0.0,0,0,30.5,0.800570
4,1/1/2015,Quarter1,sweing,Thursday,6,0.80,25.90,1170.0,1920,50,0.0,0,0,56.0,0.800382
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1192,3/11/2015,Quarter2,finishing,Wednesday,10,0.75,2.90,NaN,960,0,0.0,0,0,8.0,0.628333
1193,3/11/2015,Quarter2,finishing,Wednesday,8,0.70,3.90,NaN,960,0,0.0,0,0,8.0,0.625625
1194,3/11/2015,Quarter2,finishing,Wednesday,7,0.65,3.90,NaN,960,0,0.0,0,0,8.0,0.625625
1195,3/11/2015,Quarter2,finishing,Wednesday,9,0.75,2.90,NaN,1800,0,0.0,0,0,15.0,0.505889
1196,3/11/2015,Quarter2,finishing,Wednesday,6,0.70,2.90,NaN,720,0,0.0,0,0,6.0,0.394722

In [ ]:
X = df.drop(['date','actual_productivity'],axis=1)
X

,quarter,department,day,team,targeted_productivity,smv,wip,over_time,incentive,idle_time,idle_men,no_of_style_change,no_of_workers
0,Quarter1,sweing,Thursday,8,0.80,26.16,1108.0,7080,98,0.0,0,0,59.0
1,Quarter1,finishing,Thursday,1,0.75,3.94,NaN,960,0,0.0,0,0,8.0
2,Quarter1,sweing,Thursday,11,0.80,11.41,968.0,3660,50,0.0,0,0,30.5
3,Quarter1,sweing,Thursday,12,0.80,11.41,968.0,3660,50,0.0,0,0,30.5
4,Quarter1,sweing,Thursday,6,0.80,25.90,1170.0,1920,50,0.0,0,0,56.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1192,Quarter2,finishing,Wednesday,10,0.75,2.90,NaN,960,0,0.0,0,0,8.0
1193,Quarter2,finishing,Wednesday,8,0.70,3.90,NaN,960,0,0.0,0,0,8.0
1194,Quarter2,finishing,Wednesday,7,0.65,3.90,NaN,960,0,0.0,0,0,8.0
1195,Quarter2,finishing,Wednesday,9,0.75,2.90,NaN,1800,0,0.0,0,0,15.0
1196,Quarter2,finishing,Wednesday,6,0.70,2.90,NaN,720,0,0.0,0,0,6.0

In [ ]:
y = df['actual_productivity']
y

0       0.940725
1       0.886500
2       0.800570
3       0.800570
4       0.800382
          ...
1192    0.628333
1193    0.625625
1194    0.625625
1195    0.505889
1196    0.394722
Name: actual_productivity, Length: 1197, dtype: float64

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
X_train.isnull().sum()

quarter                    0
department                 0
day                        0
team                       0
targeted_productivity      0
smv                        0
wip                      415
over_time                  0
incentive                  0
idle_time                  0
idle_men                   0
no_of_style_change         0
no_of_workers              0
dtype: int64

In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(strategy='mean')
X_train['wip'] = imputer.fit_transform(X_train[['wip']])
X_test['wip'] = imputer.transform(X_test[['wip']])

In [ ]:
X_train.isnull().sum()

quarter                  0
department               0
day                      0
team                     0
targeted_productivity    0
smv                      0
wip                      0
over_time                0
incentive                0
idle_time                0
idle_men                 0
no_of_style_change       0
no_of_workers            0
dtype: int64

In [ ]:
categorical_data=df[['quarter','department','day']]
print(categorical_data)

       quarter  department        day
0     Quarter1      sweing   Thursday
1     Quarter1  finishing    Thursday
2     Quarter1      sweing   Thursday
3     Quarter1      sweing   Thursday
4     Quarter1      sweing   Thursday
...        ...         ...        ...
1192  Quarter2   finishing  Wednesday
1193  Quarter2   finishing  Wednesday
1194  Quarter2   finishing  Wednesday
1195  Quarter2   finishing  Wednesday
1196  Quarter2   finishing  Wednesday

[1197 rows x 3 columns]

In [ ]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()

for x in categorical_data:
  X_train[x] = label_encoder.fit_transform(X_train[x])
  X_test[x] = label_encoder.fit_transform(X_test[x])

In [ ]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()

numerical = df.drop(['date','quarter','department','day','actual_productivity'],axis=1)
print(numerical)

      team  targeted_productivity    smv     wip  over_time  incentive  \
0        8                   0.80  26.16  1108.0       7080         98
1        1                   0.75   3.94     NaN        960          0
2       11                   0.80  11.41   968.0       3660         50
3       12                   0.80  11.41   968.0       3660         50
4        6                   0.80  25.90  1170.0       1920         50
...    ...                    ...    ...     ...        ...        ...
1192    10                   0.75   2.90     NaN        960          0
1193     8                   0.70   3.90     NaN        960          0
1194     7                   0.65   3.90     NaN        960          0
1195     9                   0.75   2.90     NaN       1800          0
1196     6                   0.70   2.90     NaN        720          0

      idle_time  idle_men  no_of_style_change  no_of_workers
0           0.0         0                   0           59.0
1           0.0         0                   0            8.0
2           0.0         0                   0           30.5
3           0.0         0                   0           30.5
4           0.0         0                   0           56.0
...         ...       ...                 ...            ...
1192        0.0         0                   0            8.0
1193        0.0         0                   0            8.0
1194        0.0         0                   0            8.0
1195        0.0         0                   0           15.0
1196        0.0         0                   0            6.0

[1197 rows x 10 columns]

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error


lr = LinearRegression()
lr.fit(X_train, y_train)
lr_score = lr.score(X_test, y_test)
print(lr_score)

0.1868351155945941
0.3419611538765016
0.5488905063949057